spring.application.name=E-Commerce
spring.profiles.active=dev
#  DB config
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/team2_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Log config


