spring.application.name=E-Commerce
spring.profiles.active=dev
#  DB config
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/team2_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}


# cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Log config

# upload file
# Gi?i h?n dung l??ng file ??n l?
spring.servlet.multipart.max-file-size=3MB
# Gi?i h?n t?ng dung l??ng request
spring.servlet.multipart.max-request-size=10MB
# Gi?i h?n kích th??c t?i ?a c?a toàn b? n?i dung Request (các req th??ng)
server.tomcat.max-http-form-post-size=2MB
